name:                dynamics
version:             0.1.0.0
github:              "ahaym/dynamics"
license:             BSD3
author:              "Mark Hay"
maintainer:          "mah6@williams.edu"
copyright:           "2019 Mark Hay"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Creative Dynamics Projects

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-cairo
- gloss
- process
- colour
- mtl
- containers

library:
  source-dirs: src

executables:
  circle:
    main:                Main.hs
    source-dirs:         projects/circle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  henon:
    main:                Main.hs
    source-dirs:         projects/henon
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - dynamics
  cascade:
    main:                Main.hs
    source-dirs:         projects/cascade
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  quadratic:
    main:                Main.hs
    source-dirs:         projects/quadratic
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
    - colour
  julia:
    main:                Main.hs
    source-dirs:         projects/julia
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  mandelbrot:
    main:                Main.hs
    source-dirs:         projects/mandelbrot
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  c2d:
    main:                Main.hs
    source-dirs:         projects/c2d
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  lyapunov:
    main:                Main.hs
    source-dirs:         projects/lyapunov
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
    - numeric-tools
    - ad
  logistic:
    main:                Main.hs
    source-dirs:         projects/logistic
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  predator:
    main:                Main.hs
    source-dirs:         projects/predator
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  ldiff:
    main:                Main.hs
    source-dirs:         projects/ldiff
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
    - random
  diff3d:
    main:                Main.hs
    source-dirs:         projects/lorenz
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
  heat:
    main:                Main.hs
    source-dirs:         projects/heat
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
    - random
  bz:
    main:                Main.hs
    source-dirs:         projects/bz
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - dynamics
    - random

tests:
  dynamics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamics
